              
[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200

lib_deps =
    adafruit/Adafruit BMP280 Library @ ^2.6.8
    adafruit/Adafruit BME280 Library @ ^2.2.4
    adafruit/Adafruit Unified Sensor @ ^1.1.14
    mikalhart/TinyGPSPlus @ ^1.0.3
    paulstoffregen/OneWire
    milesburton/DallasTemperature
    https://github.com/ttlappalainen/NMEA2000.git
    https://github.com/sparkfun/SparkFun_LSM6DS3_Arduino_Library.git
    adafruit/Adafruit LIS3MDL @ ^1.1.2
   https://github.com/arduino-libraries/MadgwickAHRS.git